### ISSUE TITLE
Broken header reference in function signature type inference section

### ISSUE THREAD

**Issue by FenstonSingel** [JetBrains/kotlin-spec#110]
[This line](https://github.com/Kotlin/kotlin-spec/blob/3b01ae91f711a62740b2fdc220cfc670f8d15d3a/docs/src/md/kotlin.core/type-inference.md?plain=1#L457) in particular is affected: reference `[function declarations]` resolves to nowhere due to the use of a plural form.

**Comment by ice-phoenix** [comment]
Fixed in 742ef9ac85e2abdf2720d172c0ca8bc72ee7e58d
