### ISSUE TITLE
Missing KSP specification

### ISSUE THREAD

**Issue by janknezik** [JetBrains/kotlin-spec#13]
I am still missing KSP specification for Servlets written in Kotlin. Please, can you make one? I found it a blockage point for making Kotlin more widespread on Kotlin(Java) EE environment.

**Comment by yole** [comment]
This repository is about the specification for the Kotlin language, not for other technologies related to Kotlin. The Kotlin team at JetBrains currently has no plans to support a Kotlin-based equivalent to JSP, but the community is welcome to create such a project.
