### ISSUE TITLE
Is keyword "this" in memberAccessOperator an identifier or thisExpression?

### ISSUE THREAD

**Issue by bitcalc** [JetBrains/kotlin-spec#30]
In the `psi/examples/collections/ArrayList.kt` grammar test file, an expression uses "this" in the following way:

```
class ArrayList<T> : IMutableList<T> {
    ...
    override fun remove() {
      checkVersion()
      val result = ArrayList.this.remove(index - 1)
      ...
    }
  }
```

The expected antlrtree is:
```
      propertyDeclaration
        VAL("val")
        variableDeclaration
          simpleIdentifier
            Identifier("result")
        ASSIGNMENT("=")
        expression
          disjunction
            conjunction
              equality
                comparison
                  infixOperation
                    elvisExpression
                      infixFunctionCall
                        rangeExpression
                          additiveExpression
                            multiplicativeExpression
                              asExpression
                                prefixUnaryExpression
                                  postfixUnaryExpression
                                    primaryExpression
                                      simpleIdentifier
                                        Identifier("ArrayList")
        DOT(".")
        THIS("this")
        DOT(".")
        Identifier("remove")
        LPAREN("(")
        Identifier("index")
        SUB("-")
        IntegerLiteral("1")
        RPAREN(")")

```
The ".this" is not a part of the expression. What's the semantics of "this" here? I would assume that it has the same semantic meaning as in Java, i.e., it refers to an instance of ArrayList. Is this a bug in the grammar?

**Comment by bitcalc** [comment]
The `navigationSuffix` rule only has `class`:

```
navigationSuffix
    : NL* memberAccessOperator NL* (simpleIdentifier | parenthesizedExpression | CLASS)
    ;
```
It seems to make more sense if "this" and "super" are included just like `CLASS`, right?

**Comment by belyaev-mikhail** [comment]
> 
> 
> In the `psi/examples/collections/ArrayList.kt` grammar test file, an expression uses "this" in the following way:
> 
> ```
> class ArrayList<T> : IMutableList<T> {
>     ...
>     override fun remove() {
>       checkVersion()
>       val result = ArrayList.this.remove(index - 1)
>       ...
>     }
>   }
> ```
> 

This is incorrect Kotlin. As simple as that.
You cannot use `this` like this (pun not intended).

**Comment by belyaev-mikhail** [comment]
Not all psi examples are correct Kotlin samples, some of them involve syntax allowed by the compiler only to be caught at later stages to produce more meaningful error messages.

The grammar does not allow these.

**Comment by bitcalc** [comment]
Got it. Thanks.
