### ISSUE TITLE
Talk about "bare types" (parameterized types without parameters)

### ISSUE THREAD

**Issue by ice-phoenix** [JetBrains/kotlin-spec#56]
Bare types can be encountered, for example, in [type checking](https://kotlinlang.org/spec/expressions.html#type-checking-expressions) or [cast](https://kotlinlang.org/spec/expressions.html#cast-expressions) expressions, and are somewhat related to [runtime-available types](https://kotlinlang.org/spec/runtime-type-information.html#runtime-available-types).

Also, they currently have some problems (see [KT-15533](https://youtrack.jetbrains.com/issue/KT-15533) / [KT-15706](https://youtrack.jetbrains.com/issue/KT-15706)).

**Comment by belyaev-mikhail** [comment]
I'll write it

**Comment by belyaev-mikhail** [comment]
Done in draft
