### ISSUE TITLE
Systemically replace "undefined behavior" with "unspecified behavior"

### ISSUE THREAD

**Issue by elizarov** [JetBrains/kotlin-spec#63]
The term "_undefined behavior_" is generally associated with C/C++, where it means "program my produce arbitrary results", while in Kotlin, especially on JVM, such arbitrary behaviors are not possible. Some constructs may simply behave in _unspecified_ ways. 

P.S. The fact that K/N currently allows truly undefined behaviors in C/C++ sense is not relevant. I still think a less scary wording should be used.

**Comment by belyaev-mikhail** [comment]
Fair point.

Changed in 9d3da3f
