### ISSUE TITLE
Add SAM(lambda) conversion syntax

### ISSUE THREAD

**Issue by ice-phoenix** [JetBrains/kotlin-spec#80]
The following syntax for SAM conversion is supported

```kotlin
val lambda = { "OK" }

fun box() = Sam(lambda).get()

fun interface Sam {
    fun get(): String
}
```

**Comment by belyaev-mikhail** [comment]
Maybe we should just treat this as a fake constructor/constructor function?

**Comment by ice-phoenix** [comment]
> Maybe we should just treat this as a fake constructor/constructor function?

Yeah, that's exactly what I added to the spec =)
