### ISSUE TITLE
Set of restricted chars for JVM 

### ISSUE THREAD

**Issue by koperagen** [JetBrains/kotlin-spec#86]
I've noticed that despite following statement in [syntax.md#identifiers](https://github.com/Kotlin/kotlin-spec/blob/release/docs/src/md/kotlin.core/syntax.md#identifiers), Kotlin JVM compiler is fine with escaped identifiers with '(' in it. I've also found this [checker](https://github.com/JetBrains/kotlin/blob/1.5.30/compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/JvmSimpleNameBacktickChecker.kt#L28) which seems to exactly follow JVM specification
> Note: for example, the following characters are not allowed in identifiers used as declaration names on the JVM platform even when escaped due to JVM restrictions: (, ), {, }, [, ], .

**Comment by belyaev-mikhail** [comment]
Thanks for noticing! Fixed in develop 03ec014
